### ISSUE TITLE
File upload done. ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The first service (module) you upload to a new application must be the 'default' service (module). Please upload a version of the 'default' service (module) before uploading a version for the 'backend' service (module). See the documentation for more information. Python: (https://developers.google.com/appengine/docs/python/modules/#Python_Uploading%%20modules) Java: (https://developers.google.com/appengine/docs/java/modules/#Java_Uploading%%20modules)

### ISSUE THREAD

**Issue by skeita96** [google/nomulus#2232]
> Task :services:backend:appengineDeploy FAILED
Resolve mutations for :reportUploader (Thread[Execution worker Thread 3,5,main]) started.
:reportUploader (Thread[Execution worker Thread 3,5,main]) started.

Help me

**Comment by GuillaumeBlanchet** [comment]
I had the same issue. Since, there was no simple way to change the order without causing potential issues, I decided to run twice the deploy command with the "continue" flag:

$ ./nom_build appengineDeploy --environment=alpha --continue

This will fail to deploy "backend" and "bsa" because they are both before the "default" service, but it will deploy the default service, and then you can enter the command again:

$ ./nom_build appengineDeploy --environment=alpha

and they will be deployed without error since the last command deployed the default service.
